from itertools import islice

COCO_WHOLEBODY = {
                            # Body (17 keypoints)
                            "0": "nose",
                            "1": "left_eye",
                            "2": "right_eye",
                            "3": "left_ear",
                            "4": "right_ear",
                            "5": "left_shoulder",
                            "6": "right_shoulder",
                            "7": "left_elbow",
                            "8": "right_elbow",
                            "9": "left_wrist",
                            "10": "right_wrist",
                            "11": "left_hip",
                            "12": "right_hip",
                            "13": "left_knee",
                            "14": "right_knee",
                            "15": "left_ankle",
                            "16": "right_ankle",

                            # Feet (6 keypoints)
                            "17": "left_big_toe",
                            "18": "left_small_toe",
                            "19": "left_heel",
                            "20": "right_big_toe",
                            "21": "right_small_toe",
                            "22": "right_heel",

                            # Face (68 keypoints)
                            # Using a standard 68-point face layout:
                            # Jaw (17 points): 23-39
                            "23": "face_jaw_0",
                            "24": "face_jaw_1",
                            "25": "face_jaw_2",
                            "26": "face_jaw_3",
                            "27": "face_jaw_4",
                            "28": "face_jaw_5",
                            "29": "face_jaw_6",
                            "30": "face_jaw_7",
                            "31": "face_jaw_8",
                            "32": "face_jaw_9",
                            "33": "face_jaw_10",
                            "34": "face_jaw_11",
                            "35": "face_jaw_12",
                            "36": "face_jaw_13",
                            "37": "face_jaw_14",
                            "38": "face_jaw_15",
                            "39": "face_jaw_16",
                            # Left Eyebrow (5 points): 40-44
                            "40": "face_left_eyebrow_0",
                            "41": "face_left_eyebrow_1",
                            "42": "face_left_eyebrow_2",
                            "43": "face_left_eyebrow_3",
                            "44": "face_left_eyebrow_4",
                            # Right Eyebrow (5 points): 45-49
                            "45": "face_right_eyebrow_0",
                            "46": "face_right_eyebrow_1",
                            "47": "face_right_eyebrow_2",
                            "48": "face_right_eyebrow_3",
                            "49": "face_right_eyebrow_4",
                            # Nose (9 points): 50-58
                            "50": "face_nose_bridge_0",
                            "51": "face_nose_bridge_1",
                            "52": "face_nose_bridge_2",
                            "53": "face_nose_bridge_3",
                            "54": "face_nose_tip_0",
                            "55": "face_nose_tip_1",
                            "56": "face_nose_tip_2",
                            "57": "face_nose_tip_3",
                            "58": "face_nose_tip_4",
                            # Left Eye (6 points): 59-64
                            "59": "face_left_eye_0",
                            "60": "face_left_eye_1",
                            "61": "face_left_eye_2",
                            "62": "face_left_eye_3",
                            "63": "face_left_eye_4",
                            "64": "face_left_eye_5",
                            # Right Eye (6 points): 65-70
                            "65": "face_right_eye_0",
                            "66": "face_right_eye_1",
                            "67": "face_right_eye_2",
                            "68": "face_right_eye_3",
                            "69": "face_right_eye_4",
                            "70": "face_right_eye_5",
                            # Mouth Outer (12 points): 71-82
                            "71": "face_mouth_outer_0",
                            "72": "face_mouth_outer_1",
                            "73": "face_mouth_outer_2",
                            "74": "face_mouth_outer_3",
                            "75": "face_mouth_outer_4",
                            "76": "face_mouth_outer_5",
                            "77": "face_mouth_outer_6",
                            "78": "face_mouth_outer_7",
                            "79": "face_mouth_outer_8",
                            "80": "face_mouth_outer_9",
                            "81": "face_mouth_outer_10",
                            "82": "face_mouth_outer_11",
                            # Mouth Inner (8 points): 83-90
                            "83": "face_mouth_inner_0",
                            "84": "face_mouth_inner_1",
                            "85": "face_mouth_inner_2",
                            "86": "face_mouth_inner_3",
                            "87": "face_mouth_inner_4",
                            "88": "face_mouth_inner_5",
                            "89": "face_mouth_inner_6",
                            "90": "face_mouth_inner_7",

                            # Hands (42 keypoints: 21 per hand)
                            # Left Hand (21 points): 91-111
                            "91": "left_hand_wrist",
                            "92": "left_hand_thumb_1",
                            "93": "left_hand_thumb_2",
                            "94": "left_hand_thumb_3",
                            "95": "left_hand_thumb_tip",
                            "96": "left_hand_index_1",
                            "97": "left_hand_index_2",
                            "98": "left_hand_index_3",
                            "99": "left_hand_index_tip",
                            "100": "left_hand_middle_1",
                            "101": "left_hand_middle_2",
                            "102": "left_hand_middle_3",
                            "103": "left_hand_middle_tip",
                            "104": "left_hand_ring_1",
                            "105": "left_hand_ring_2",
                            "106": "left_hand_ring_3",
                            "107": "left_hand_ring_tip",
                            "108": "left_hand_pinky_1",
                            "109": "left_hand_pinky_2",
                            "110": "left_hand_pinky_3",
                            "111": "left_hand_pinky_tip",

                            # Right Hand (21 points): 112-132
                            "112": "right_hand_wrist",
                            "113": "right_hand_thumb_1",
                            "114": "right_hand_thumb_2",
                            "115": "right_hand_thumb_3",
                            "116": "right_hand_thumb_tip",
                            "117": "right_hand_index_1",
                            "118": "right_hand_index_2",
                            "119": "right_hand_index_3",
                            "120": "right_hand_index_tip",
                            "121": "right_hand_middle_1",
                            "122": "right_hand_middle_2",
                            "123": "right_hand_middle_3",
                            "124": "right_hand_middle_tip",
                            "125": "right_hand_ring_1",
                            "126": "right_hand_ring_2",
                            "127": "right_hand_ring_3",
                            "128": "right_hand_ring_tip",
                            "129": "right_hand_pinky_1",
                            "130": "right_hand_pinky_2",
                            "131": "right_hand_pinky_3",
                            "132": "right_hand_pinky_tip",
                            "133": "head_centroid", 
                            "134": "body_centroid"
                        }


COCO = dict(islice(COCO_WHOLEBODY.items(), 17))